export const SET_DANH_SACH_PHIM ='SET_DANH_SACH_PHIM';
export const SET_FILM_DANG_CHIEU ='SET_FILM_DANG_CHIEU';
export const SET_FILM_SAP_CHIEU ='SET_FILM_SAP_CHIEU';

export const THEM_PHIM_UPLOAD_HINH ='THEM_PHIM_UPLOAD_HINH';
export const THONG_TIN_PHIM_EDIT ='THONG_TIN_PHIM_EDIT';
export const CAP_NHAT_PHIM ='CAP_NHAT_PHIM';

